name: Push Events
on:
  push:
    branches:
      - main
      - test
jobs:
  show-info:
    runs-on: ubuntu-latest
    steps:
      - name: Info
        run: |
          echo "This is a push event on the main or test branch"
