name: Push Events
on:
  schedule:
    - cron: '*/5 * * * *' #Every 5 minutes
jobs:
  show-info:
    runs-on: ubuntu-latest
    steps:
      - name: Info
        run: |
          echo "This is a push event on the main or test branch"
