name: Push Events
on:
  push:
    branches:
      - main
jobs:
  show-info:
    runs-on: ubuntu-latest
    env:
      APP_MODE: ${{ vars.APP_MODE }}
    steps:
      - name: Display Env Variable
        run: echo "This is $APP_MODE mode"
