name: Env variable example
on:
  push:
    branches:
      - main
jobs:
  example:
    runs-on: ubuntu-latest
    env:
      MY_VARIABLE: "Hello from Env Variable"
    steps:
      - name: Display Env Variable
        run: echo "MY_VARIABLE:$MY_VARIABLE"
