name: Example workflow
on:
  push:
    branches:
      - main
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use API key
        run: echo "API_KEY is ${{ secrets.API_KEY }}"
